### PR TITLE
WIP: Add rubocop

### PR DESCRIPTION
**Pull request by nadjaheitmann**
@amirfefer After our meeting today, I set up some basic CI for rubocop checks. We can discuss this further, once at least #3 and #4 are merged.

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@ofedoren Any idea what to do with this? As far as I know, you do not use rubocop for hammer-cli-foreman, right?

**Comment by ofedoren** [comment]
@nadjaheitmann, yeap, we don't have an "official" rubocop file and CI for that since it would require a lot of changes (automated but still).

Rubocop is not enforced to be used anyway, it just depends on the devs whether they want to use that or not :)

**Comment by nadjaheitmann** [comment]
@ofedoren Okay, thanks. Not sure who is on the "devs" team right now to decide about this ;)

**Comment by nadjaheitmann** [comment]
Closing for now as rubocop is not needed for hammer at the moment.

**Pull request closed without merging**
