### PR TITLE
Fixes #10 - Add resource for import-classes command

### LINKED ISSUE #10: import-classes not fully available
My system configuration:
`hammer --version
hammer (3.0.0.pre.develop)
 * hammer_cli_csv (2.3.1)
 * hammer_cli_foreman (3.0.0.pre.develop)
 * hammer_cli_foreman_admin (1.1.0)
 * hammer_cli_foreman_remote_execution (0.2.1)
 * hammer_cli_foreman_tasks (0.0.16)
 * hammer_cli_katello (1.1.1.pre.master)
` 

Command:
`hammer -s 192.168.211.1 --reload-cache proxy import-classes --help`

Output for core (pre-extraction): 
Usage:
    hammer proxy import-classes [OPTIONS]

Options:
 --dryrun                                      Do not run the import
 --except EXCEPT                               Optional comma-delimited string containing either 'new', 'updated', or 'obsolete' that is used to limit the imported Puppet classes
 --id ID                                        
 --location[-id|-title]                        Set the current location context for the request
 --name NAME                                   Name to search by
 --organization[-id|-title]                    Set the current organization context for the request
 --puppet-environment[-id]                     Name/Id of associated puppet environment
 -h, --help  

Output with plugin:
Usage:
    hammer proxy import-classes [OPTIONS]

Options:
 --dryrun                      Do not run the import
 -h, --help                    Print help

### PR DESCRIPTION
**Pull request by ofedoren**

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@ekohl And here ;)

**Comment by ekohl** [comment]
Also a merge conflict here.

**Comment by tbrisker** [comment]
gah looks like gh conflict fixing didn't work as expected, pushing rebase now

**Review by tbrisker — APPROVED** [review]
Thanks @ofedoren !

**Pull request merged**
