### PR TITLE
WIP: Add unit tests

### PR DESCRIPTION
**Pull request by nadjaheitmann**
* add unit tests

### CODE REVIEW

**Comment by ofedoren** [comment]
Although I didn't test that, looks okay. Not sure if you really want those changes since afterwards you'll need to rename things again :) I've noticed there are 5 PRs, and maybe I overlooked, but I didn't see a PR that actually adds here what is being extracted in https://github.com/amirfefer/hammer-cli-foreman/pull/1. And I assume that the initial state of this plugin is not quite right also.

I'd suggest to simply use https://github.com/amirfefer/hammer-cli-foreman/pull/1 as initial state for hammer-cli-foreman and make changes for this plugin accordingly (for example ensure that all that is being extracted is being added here). And only then do additional stuff like extending and ensuring it actually works (since in this case we would have a reference (https://github.com/amirfefer/hammer-cli-foreman/pull/1) to test with)

**Comment by nadjaheitmann** [comment]
Thanks @ofedoren for the input. The initial state of this plugin plus #1 and #3 actually do what you have suggested: They add to the plugin what @amirfefer has removed in https://github.com/amirfefer/hammer-cli-foreman/pull/. 

About the renaming: I agree that it is some effort to rename things back, eventually. But changing names has the advantage that things can be tested side by side with the original code AND with https://github.com/amirfefer/hammer-cli-foreman/pull/. So it is a matter of taste, I guess :)  

This PR (#5) should add unit tests eventually :) So how shall we proceed with #1 and #3?

**Comment by ofedoren** [comment]
@nadjaheitmann, as long as I don't need to do renaming, I'm fine with that :D

Regarding #1 and #3 it can be merged so we have something to test afterwards, but it depends more on the maintainer of this plugin, not me :)

**Comment by nadjaheitmann** [comment]
@ofedoren I am fine with doing the renaming :D 
Of course @amirfefer has the final word about merging #1 and #3 :)

**Comment by nadjaheitmann** [comment]
Closed in favor of #8

**Pull request closed without merging**
