### PR TITLE
Fix associated commands

### PR DESCRIPTION
**Pull request by amirfefer**

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
Thanks @amirfefer Seems to work. FYI: There is an issue with the Foreman plugin I found during testing: https://github.com/theforeman/foreman_puppet/issues/174

**Comment by nadjaheitmann** [comment]
@ofedoren Do you mind checking this?

**Review by ofedoren — APPROVED** [review]
I was able to run the commands and it seems to be working just fine (couldn't test fully I got `uninitialized constant Environment` on the server, but not a blocker).

Needs to refactor a bit, but not prio and not a blocker.

**Comment by nadjaheitmann** [comment]
@ekohl And here ;)

**Comment by ekohl** [comment]
There's a merge conflict now.

**Pull request merged**
